package user.model;
// Generated May 12, 2016 9:48:09 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name="Users"
    ,schema="dbo"
    ,catalog="WSAppDB2"
)
public class Users  implements java.io.Serializable {


     private int id;
     private String login;
     private String password;
     private Integer studentId;

    public Users() {
    }

	
    public Users(int id) {
        this.id = id;
    }
    public Users(int id, String login, String password, Integer studentId) {
       this.id = id;
       this.login = login;
       this.password = password;
       this.studentId = studentId;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="login", length=100)
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }

    
    @Column(name="password", length=100)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="studentID")
    public Integer getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }




}


